# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth_form.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(422, 494)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.input_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.input_groupBox.setAutoFillBackground(False)
        self.input_groupBox.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"gridline-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.input_groupBox.setFlat(False)
        self.input_groupBox.setCheckable(False)
        self.input_groupBox.setObjectName("input_groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.input_groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.username_label = QtWidgets.QLabel(self.input_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username_label.setFont(font)
        self.username_label.setObjectName("username_label")
        self.horizontalLayout_4.addWidget(self.username_label)
        self.username_line_edit = QtWidgets.QLineEdit(self.input_groupBox)
        self.username_line_edit.setObjectName("username_line_edit")
        self.horizontalLayout_4.addWidget(self.username_line_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.password_label = QtWidgets.QLabel(self.input_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.horizontalLayout_5.addWidget(self.password_label)
        self.password_line_edit = QtWidgets.QLineEdit(self.input_groupBox)
        self.password_line_edit.setObjectName("password_line_edit")
        self.horizontalLayout_5.addWidget(self.password_line_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.password_push_button = QtWidgets.QPushButton(self.input_groupBox)
        self.password_push_button.setObjectName("password_push_button")
        self.verticalLayout.addWidget(self.password_push_button)
        self.password_info_label_2 = QtWidgets.QLabel(self.input_groupBox)
        self.password_info_label_2.setText("")
        self.password_info_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.password_info_label_2.setObjectName("password_info_label_2")
        self.verticalLayout.addWidget(self.password_info_label_2)
        self.password_info_label = QtWidgets.QLabel(self.input_groupBox)
        self.password_info_label.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password_info_label.setFont(font)
        self.password_info_label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.password_info_label.setText("")
        self.password_info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.password_info_label.setObjectName("password_info_label")
        self.verticalLayout.addWidget(self.password_info_label)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_6.addWidget(self.input_groupBox)
        self.output_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.output_groupBox.setEnabled(False)
        self.output_groupBox.setAutoFillBackground(False)
        self.output_groupBox.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.output_groupBox.setFlat(False)
        self.output_groupBox.setCheckable(False)
        self.output_groupBox.setChecked(False)
        self.output_groupBox.setObjectName("output_groupBox")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.output_groupBox)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.output_groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.first_type_overlaying_label = QtWidgets.QLabel(self.output_groupBox)
        self.first_type_overlaying_label.setObjectName("first_type_overlaying_label")
        self.horizontalLayout.addWidget(self.first_type_overlaying_label)
        self.lcdNumber = QtWidgets.QLCDNumber(self.output_groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lcdNumber.setProperty("value", 0.0)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout.addWidget(self.lcdNumber)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.second_type_overlaying_label = QtWidgets.QLabel(self.output_groupBox)
        self.second_type_overlaying_label.setObjectName("second_type_overlaying_label")
        self.horizontalLayout_2.addWidget(self.second_type_overlaying_label)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.output_groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lcdNumber_2.setFont(font)
        self.lcdNumber_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lcdNumber_2.setProperty("value", 0.0)
        self.lcdNumber_2.setProperty("intValue", 0)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.horizontalLayout_2.addWidget(self.lcdNumber_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.third_type_overlaying_label = QtWidgets.QLabel(self.output_groupBox)
        self.third_type_overlaying_label.setObjectName("third_type_overlaying_label")
        self.horizontalLayout_3.addWidget(self.third_type_overlaying_label)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.output_groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lcdNumber_3.setFont(font)
        self.lcdNumber_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lcdNumber_3.setProperty("value", 0.0)
        self.lcdNumber_3.setProperty("intValue", 0)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.horizontalLayout_3.addWidget(self.lcdNumber_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.output_groupBox)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(self.output_groupBox)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_7.addWidget(self.tableWidget)
        self.horizontalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.verticalLayout_6.addWidget(self.output_groupBox)
        self.horizontalLayout_9.addLayout(self.verticalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 422, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuInput_speed_value = QtWidgets.QMenu(self.menu)
        self.menuInput_speed_value.setObjectName("menuInput_speed_value")
        self.menuDatabase = QtWidgets.QMenu(self.menubar)
        self.menuDatabase.setObjectName("menuDatabase")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionMorning = QtWidgets.QAction(MainWindow)
        self.actionMorning.setObjectName("actionMorning")
        self.actionDay = QtWidgets.QAction(MainWindow)
        self.actionDay.setObjectName("actionDay")
        self.actionEvening = QtWidgets.QAction(MainWindow)
        self.actionEvening.setObjectName("actionEvening")
        self.actionNight = QtWidgets.QAction(MainWindow)
        self.actionNight.setObjectName("actionNight")
        self.actionEntering_password_dynamic = QtWidgets.QAction(MainWindow)
        self.actionEntering_password_dynamic.setObjectName("actionEntering_password_dynamic")
        self.actionInsert = QtWidgets.QAction(MainWindow)
        self.actionInsert.setObjectName("actionInsert")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuInput_speed_value.addAction(self.actionMorning)
        self.menuInput_speed_value.addAction(self.actionDay)
        self.menuInput_speed_value.addAction(self.actionEvening)
        self.menuInput_speed_value.addAction(self.actionNight)
        self.menu.addAction(self.menuInput_speed_value.menuAction())
        self.menu.addAction(self.actionEntering_password_dynamic)
        self.menuDatabase.addAction(self.actionInsert)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.input_groupBox.setTitle(_translate("MainWindow", "Input"))
        self.username_label.setText(_translate("MainWindow", "Username"))
        self.password_label.setText(_translate("MainWindow", "Password "))
        self.password_push_button.setText(_translate("MainWindow", "OK"))
        self.output_groupBox.setTitle(_translate("MainWindow", "Output"))
        self.label_4.setText(_translate("MainWindow", "Keyboard overlaying"))
        self.first_type_overlaying_label.setText(_translate("MainWindow", "1 type"))
        self.second_type_overlaying_label.setText(_translate("MainWindow", "2 type"))
        self.third_type_overlaying_label.setText(_translate("MainWindow", "3 type"))
        self.label.setText(_translate("MainWindow", "Key time hold"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menu.setTitle(_translate("MainWindow", "Stats"))
        self.menuInput_speed_value.setTitle(_translate("MainWindow", "Entering passwod speed"))
        self.menuDatabase.setTitle(_translate("MainWindow", "Database"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionMorning.setText(_translate("MainWindow", "Morning"))
        self.actionDay.setText(_translate("MainWindow", "Day"))
        self.actionEvening.setText(_translate("MainWindow", "Evening"))
        self.actionNight.setText(_translate("MainWindow", "Night"))
        self.actionEntering_password_dynamic.setText(_translate("MainWindow", "Entering password dynamic"))
        self.actionInsert.setText(_translate("MainWindow", "Insert"))

